In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline
import streamlit as st
import mysql.connector
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String

pd.options.display.max_rows = 9999

In [2]:
pisa2022_school_df = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\pisa2022.csv", encoding='cp1252')
pisa2022_school_df

,ï»¿CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,i,Country_Region,Ranking,AverageScore
0,ALB,8,800282,800001,08MS,800,ALB03,80000,800,NON-OECD,...,331.017,223.752,305.671,230.156,289.436,0.55561,218,Albania,70,367.3
1,ALB,8,800115,800002,08MS,800,ALB03,80000,800,NON-OECD,...,284.836,364.565,304.044,347.626,352.269,0.76431,218,Albania,70,367.3
2,ALB,8,800242,800003,08MS,800,ALB01,80000,800,NON-OECD,...,289.896,338.469,316.296,324.361,343.351,1.37877,218,Albania,70,367.3
3,ALB,8,800245,800005,08MS,800,ALB08,80000,800,NON-OECD,...,165.575,246.156,238.322,275.860,227.466,1.49361,218,Albania,70,367.3
4,ALB,8,800285,800006,08MS,800,ALB03,80000,800,NON-OECD,...,461.793,514.465,510.462,490.537,503.793,0.65249,218,Albania,70,367.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,UZB,860,86000120,86007488,08MS,86000,UZB26,8600000,86000,NON-OECD,...,386.969,376.271,368.287,395.329,278.263,0.71987,218,Uzbekistan,78,351.7
613740,UZB,860,86000140,86007489,08MS,86000,UZB04,8600000,86000,NON-OECD,...,179.328,233.470,203.001,254.340,233.187,0.65541,218,Uzbekistan,78,351.7
613741,UZB,860,86000024,86007490,08MS,86000,UZB10,8600000,86000,NON-OECD,...,387.329,456.236,424.790,408.986,460.542,0.67910,218,Uzbekistan,78,351.7
613742,UZB,860,86000174,86007491,08MS,86000,UZB16,8600000,86000,NON-OECD,...,248.165,405.860,364.173,346.663,341.668,0.68618,218,Uzbekistan,78,351.7
613743,UZB,860,86000123,86007492,08MS,86000,UZB10,8600000,86000,NON-OECD,...,370.817,395.176,412.317,390.490,439.211,0.67910,218,Uzbekistan,78,351.7

In [3]:
pisa2022_school_df.dtypes

ï»¿CNT             object
CNTRYID             int64
CNTSCHID            int64
CNTSTUID            int64
CYC                object
NatCen              int64
STRATUM            object
SUBNATIO            int64
REGION              int64
OECD               object
ADMINMODE           int64
LANGTEST_QQQ        int64
LANGTEST_COG        int64
Option_ICTQ         int64
Option_WBQ          int64
Option_PQ           int64
Option_TQ           int64
Option_UH           int64
BOOKID              int64
ST001D01T           int64
ST003D02T           int64
ST003D03T           int64
ST004D01T           int64
ST250Q01JA          int64
ST250Q02JA          int64
ST250Q03JA          int64
ST250Q04JA          int64
ST250Q05JA          int64
ST250D06JA          int64
ST250D07JA          int64
ST251Q01JA          int64
ST251Q02JA          int64
ST251Q03JA          int64
ST251Q04JA          int64
ST251Q06JA          int64
ST251Q07JA          int64
ST251D08JA          int64
ST251D09JA          int64
ST253Q01JA          int64
ST254Q01JA          int64
ST254Q02JA          int64
ST254Q03JA          int64
ST254Q04JA          int64
ST254Q05JA          int64
ST254Q06JA          int64
ST255Q01JA          int64
ST256Q01JA          int64
ST256Q02JA          int64
ST256Q03JA          int64
ST256Q06JA          int64
ST256Q07JA          int64
ST256Q08JA          int64
ST256Q09JA          int64
ST256Q10JA          int64
ST230Q01JA          int64
ST005Q01JA          int64
ST006Q01JA          int64
ST006Q02JA          int64
ST006Q03JA          int64
ST006Q04JA          int64
ST006Q05JA          int64
ST007Q01JA          int64
ST008Q01JA          int64
ST008Q02JA          int64
ST008Q03JA          int64
ST008Q04JA          int64
ST008Q05JA          int64
ST258Q01JA          int64
ST259Q01JA          int64
ST259Q02JA          int64
ST019AQ01T          int64
ST019BQ01T          int64
ST019CQ01T          int64
ST022Q01TA          int64
ST226Q01JA          int64
ST125Q01NA          int64
ST126Q01TA          int64
ST127Q01TA          int64
ST127Q02TA          int64
ST127Q03TA          int64
ST260Q01JA          int64
ST260Q02JA          int64
ST260Q03JA          int64
ST062Q01TA          int64
ST062Q02TA          int64
ST062Q03TA          int64
ST267Q01JA          int64
ST267Q02JA          int64
ST267Q03JA          int64
ST267Q04JA          int64
ST267Q05JA          int64
ST267Q06JA          int64
ST267Q07JA          int64
ST267Q08JA          int64
ST034Q01TA          int64
ST034Q02TA          int64
ST034Q03TA          int64
ST034Q04TA          int64
ST034Q05TA          int64
ST034Q06TA          int64
ST038Q03NA          int64
ST038Q04NA          int64
ST038Q05NA          int64
ST038Q06NA          int64
ST038Q07NA          int64
ST038Q08NA          int64
ST038Q09JA          int64
ST038Q10JA          int64
ST038Q11JA          int64
ST265Q01JA          int64
ST265Q02JA          int64
ST265Q03JA          int64
ST265Q04JA          int64
ST266Q01JA          int64
ST266Q02JA          int64
ST266Q03JA          int64
ST266Q04JA          int64
ST266Q05JA          int64
ST294Q01JA          int64
ST294Q02JA          int64
ST294Q03JA          int64
ST294Q04JA          int64
ST294Q05JA          int64
ST295Q01JA          int64
ST295Q02JA          int64
ST295Q03JA          int64
ST295Q04JA          int64
ST295Q05JA          int64
ST326Q01JA          int64
ST326Q02JA          int64
ST326Q03JA          int64
ST326Q04JA          int64
ST326Q05JA          int64
ST326Q06JA          int64
ST322Q01JA          int64
ST322Q02JA          int64
ST322Q03JA          int64
ST322Q04JA          int64
ST322Q06JA          int64
ST322Q07JA          int64
ST307Q01JA          int64
ST307Q02JA          int64
ST307Q03JA          int64
ST307Q04JA          int64
ST307Q05JA          int64
ST307Q06JA          int64
ST307Q07JA          int64
ST307Q08JA          int64
ST307Q09JA          int64
ST307Q10JA          int64
ST309Q01JA          int64
ST309Q02JA          int64
ST309Q03JA          int64
ST309Q04JA          int64
ST309Q05JA          int64
ST309Q06JA          int64
ST309Q07JA          int64
ST309Q08JA          int64
ST309Q09JA          int64
ST309Q10JA          int64
ST301Q01JA          int64
ST301Q02JA          int64
ST301Q03JA          int64
ST301Q04JA          int64
ST301Q05JA          int64
ST301Q06JA          int64
ST301Q07JA          int64
ST301Q08JA          int64
ST301Q09JA          int64
ST301Q10JA          int64
ST343Q01JA          int64
ST343Q02JA          int64
ST343Q03JA          int64
ST343Q04JA          int64
ST343Q05JA          int64
ST343Q06JA          int64
ST343Q07JA          int64
ST343Q08JA          int64
ST343Q09JA          int64
ST343Q10JA          int64
ST311Q01JA          int64
ST311Q02JA          int64
ST311Q03JA          int64
ST311Q04JA          int64
ST311Q05JA          int64
ST311Q06JA          int64
ST311Q07JA          int64
ST311Q08JA          int64
ST311Q09JA          int64
ST311Q10JA          int64
ST315Q01JA          int64
ST315Q02JA          int64
ST315Q03JA          int64
ST315Q04JA          int64
ST315Q05JA          int64
ST315Q06JA          int64
ST315Q07JA          int64
ST315Q08JA          int64
ST315Q09JA          int64
ST315Q10JA          int64
ST303Q01JA          int64
ST303Q02JA          int64
ST303Q03JA          int64
ST303Q04JA          int64
ST303Q05JA          int64
ST303Q06JA          int64
ST303Q07JA          int64
ST303Q08JA          int64
ST305Q01JA          int64
ST305Q02JA          int64
ST305Q03JA          int64
ST305Q04JA          int64
ST305Q05JA          int64
ST305Q06JA          int64
ST305Q07JA          int64
ST305Q08JA          int64
ST305Q09JA          int64
ST305Q10JA          int64
ST345Q01JA          int64
ST345Q02JA          int64
ST345Q03JA          int64
ST345Q04JA          int64
ST345Q05JA          int64
ST345Q06JA          int64
ST345Q07JA          int64
ST345Q08JA          int64
ST345Q09JA          int64
ST345Q10JA          int64
ST313Q01JA          int64
ST313Q02JA          int64
ST313Q03JA          int64
ST313Q04JA          int64
ST313Q05JA          int64
ST313Q06JA          int64
ST313Q07JA          int64
ST313Q08JA          int64
ST313Q09JA          int64
ST313Q10JA          int64
ST263Q02JA          int64
ST263Q04JA          int64
ST263Q06JA          int64
ST016Q01NA          int64
ST059Q01TA          int64
ST059Q02JA          int64
ST296Q01JA          int64
ST296Q02JA          int64
ST296Q03JA          int64
ST296Q04JA          int64
ST272Q01JA          int64
ST273Q01JA          int64
ST273Q02JA          int64
ST273Q03JA          int64
ST273Q04JA          int64
ST273Q05JA          int64
ST273Q06JA          int64
ST273Q07JA          int64
ST270Q01JA          int64
ST270Q02JA          int64
ST270Q03JA          int64
ST270Q04JA          int64
ST285Q01JA          int64
ST285Q02JA          int64
ST285Q03JA          int64
ST285Q04JA          int64
ST285Q05JA          int64
ST285Q06JA          int64
ST285Q07JA          int64
ST285Q08JA          int64
ST285Q09JA          int64
ST283Q01JA          int64
ST283Q02JA          int64
ST283Q03JA          int64
ST283Q04JA          int64
ST283Q05JA          int64
ST283Q06JA          int64
ST283Q07JA          int64
ST283Q08JA          int64
ST283Q09JA          int64
ST275Q01WA          int64
ST275Q02WA          int64
ST275Q03WA          int64
ST275Q04WA          int64
ST275Q05WA          int64
ST275Q06WA          int64
ST275Q07WA          int64
ST275Q08WA          int64
ST275Q09WA          int64
ST276Q01JA          int64
ST276Q02JA          int64
ST276Q03JA          int64
ST276Q04JA          int64
ST276Q05JA          int64
ST276Q06JA          int64
ST276Q07JA          int64
ST276Q08JA          int64
ST276Q09JA          int64
ST276Q10JA          int64
ST268Q01JA          int64
ST268Q02JA          int64
ST268Q03JA          int64
ST268Q04JA          int64
ST268Q05JA          int64
ST268Q06JA          int64
ST268Q07JA          int64
ST268Q08JA          int64
ST268Q09JA          int64
ST290Q01WA          int64
ST290Q02WA          int64
ST290Q03WA          int64
ST290Q04WA          int64
ST290Q05WA          int64
ST290Q06WA          int64
ST290Q07WA          int64
ST290Q08WA          int64
ST290Q09WA          int64
ST291Q01JA          int64
ST291Q02JA          int64
ST291Q03JA          int64
ST291Q04JA          int64
ST291Q05JA          int64
ST291Q06JA          int64
ST291Q07JA          int64
ST291Q08JA          int64
ST291Q09JA          int64
ST291Q10JA          int64
ST289Q01WA          int64
ST289Q02JA          int64
ST289Q03WA          int64
ST289Q04JA          int64
ST289Q05WA          int64
ST289Q06JA          int64
ST289Q07JA          int64
ST289Q08WA          int64
ST289Q09WA          int64
ST289Q10WA          int64
ST289Q11WA          int64
ST289Q14JA          int64
ST293Q01JA          int64
ST293Q02JA          int64
ST293Q03JA          int64
ST293Q04JA          int64
ST293Q05JA          int64
ST293Q06JA          int64
ST293Q07JA          int64
ST293Q08JA          int64
ST293Q09JA          int64
ST292Q01JA          int64
ST292Q02JA          int64
ST292Q03JA          int64
ST292Q04JA          int64
ST292Q05JA          int64
ST292Q06JA          int64
ST297Q01JA          int64
ST297Q03JA          int64
ST297Q05JA          int64
ST297Q06JA          int64
ST297Q07JA          int64
ST297Q09JA          int64
ST300Q01JA          int64
ST300Q02JA          int64
ST300Q03JA          int64
ST300Q04JA          int64
ST300Q05JA          int64
ST300Q06JA          int64
ST300Q07JA          int64
ST300Q08JA          int64
ST300Q09JA          int64
ST300Q10JA          int64
ST327Q01JA          int64
ST327Q02JA          int64
ST327Q03JA          int64
ST327Q04JA          int64
ST327Q05JA          int64
ST327Q06JA          int64
ST327Q07JA          int64
ST327Q08JA          int64
ST330Q01WA          int64
ST330Q02WA          int64
ST330Q03WA          int64
ST330Q04WA          int64
ST330Q05WA          int64
ST330Q06WA          int64
ST330Q07WA          int64
ST330Q08WA          int64
ST330Q09WA          int64
ST330Q11WA          int64
ST330D10WA          int64
ST324Q02JA          int64
ST324Q04JA          int64
ST324Q05JA          int64
ST324Q07JA          int64
ST324Q10JA          int64
ST324Q11JA          int64
ST324Q12JA          int64
ST324Q13JA          int64
ST324Q14JA          int64
ST347Q01JA          int64
ST347Q02JA          int64
ST348Q01JA          int64
ST348Q02JA          int64
ST348Q03JA          int64
ST348Q04JA          int64
ST348Q05JA          int64
ST348Q06JA          int64
ST348Q07JA          int64
ST348Q08JA          int64
ST349Q01JA          int64
ST350Q01JA          int64
ST351Q01JA          int64
ST351Q02JA          int64
ST351Q03JA          int64
ST351Q04JA          int64
ST351Q05JA          int64
ST351Q06JA          int64
ST351Q07JA          int64
ST351Q08JA          int64
ST352Q01JA          int64
ST352Q02JA          int64
ST352Q03JA          int64
ST352Q04JA          int64
ST352Q05JA          int64
ST352Q06JA          int64
ST352Q07JA          int64
ST352Q08JA          int64
ST353Q01JA          int64
ST353Q02JA          int64
ST353Q03JA          int64
ST353Q04JA          int64
ST353Q05JA          int64
ST353Q06JA          int64
ST353Q07JA          int64
ST353Q08JA          int64
ST354Q01JA          int64
ST354Q02JA          int64
ST354Q03JA          int64
ST354Q04JA          int64
ST354Q05JA          int64
ST354Q06JA          int64
ST354Q07JA          int64
ST354Q08JA          int64
ST354Q09JA          int64
ST354Q10JA          int64
ST355Q01JA          int64
ST355Q02JA          int64
ST355Q03JA          int64
ST355Q04JA          int64
ST355Q05JA          int64
ST355Q06JA          int64
ST355Q07JA          int64
ST355Q08JA          int64
ST356Q01JA          int64
ST331Q01JA          int64
ST331Q02JA          int64
ST331Q03JA          int64
IC170Q01JA          int64
IC170Q02JA          int64
IC170Q03JA          int64
IC170Q04JA          int64
IC170Q05JA          int64
IC170Q06JA          int64
IC170Q07JA          int64
IC171Q01JA          int64
IC171Q02JA          int64
IC171Q03JA          int64
IC171Q04JA          int64
IC171Q05JA          int64
IC171Q06JA          int64
IC172Q01JA          int64
IC172Q02JA          int64
IC172Q03JA          int64
IC172Q04JA          int64
IC172Q05JA          int64
IC172Q06JA          int64
IC172Q07JA          int64
IC172Q08JA          int64
IC172Q09JA          int64
IC173Q01JA          int64
IC173Q02JA          int64
IC173Q03JA          int64
IC173Q04JA          int64
IC174Q01JA          int64
IC174Q02JA          int64
IC174Q03JA          int64
IC174Q04JA          int64
IC174Q05JA          int64
IC174Q06JA          int64
IC174Q07JA          int64
IC174Q08JA          int64
IC174Q09JA          int64
IC174Q10JA          int64
IC175Q01JA          int64
IC175Q02JA          int64
IC175Q03JA          int64
IC175Q05JA          int64
IC176Q01JA          int64
IC176Q02JA          int64
IC176Q03JA          int64
IC176Q04JA          int64
IC176Q05JA          int64
IC176Q06JA          int64
IC176Q07JA          int64
IC176Q08JA          int64
IC184Q01JA          int64
IC184Q02JA          int64
IC184Q03JA          int64
IC184Q04JA          int64
IC177Q01JA          int64
IC177Q02JA          int64
IC177Q03JA          int64
IC177Q04JA          int64
IC177Q05JA          int64
IC177Q06JA          int64
IC177Q07JA          int64
IC178Q01JA          int64
IC178Q02JA          int64
IC178Q03JA          int64
IC178Q04JA          int64
IC178Q05JA          int64
IC178Q06JA          int64
IC178Q07JA          int64
IC179Q01JA          int64
IC179Q02JA          int64
IC179Q03JA          int64
IC179Q04JA          int64
IC179Q05JA          int64
IC179Q06JA          int64
IC180Q01JA          int64
IC180Q02JA          int64
IC180Q03JA          int64
IC180Q04JA          int64
IC180Q05JA          int64
IC180Q06JA          int64
IC180Q07JA          int64
IC180Q08JA          int64
IC181Q01JA          int64
IC181Q02JA          int64
IC181Q03JA          int64
IC181Q04JA          int64
IC182Q01JA          int64
IC182Q02JA          int64
IC182Q03JA          int64
IC183Q01JA          int64
IC183Q02JA          int64
IC183Q03JA          int64
IC183Q04JA          int64
IC183Q05JA          int64
IC183Q07JA          int64
IC183Q08JA          int64
IC183Q09JA          int64
IC183Q10JA          int64
IC183Q12JA          int64
IC183Q13JA          int64
IC183Q14JA          int64
IC183Q15JA          int64
IC183Q16JA          int64
EFFORT1             int64
EFFORT2             int64
OCOD1               int64
OCOD2               int64
OCOD3               int64
PROGN               int64
AGE               float64
GRADE               int64
ISCEDP              int64
IMMIG               int64
COBN_S              int64
COBN_M              int64
COBN_F              int64
LANGN               int64
REPEAT              int64
MISSSC              int64
SKIPPING            int64
TARDYSD             int64
EXERPRAC            int64
STUDYHMW            int64
WORKPAY             int64
WORKHOME            int64
EXPECEDU            int64
MATHPREF            int64
MATHEASE            int64
MATHMOT             int64
DURECEC             int64
BSMJ              float64
SISCO               int64
RELATST           float64
BELONG            float64
BULLIED           float64
FEELSAFE          float64
SCHRISK           float64
PERSEVAGR           int64
CURIOAGR          float64
COOPAGR             int64
EMPATAGR            int64
ASSERAGR            int64
STRESAGR            int64
EMOCOAGR            int64
INFOSEEK          float64
FAMSUP            float64
DISCLIM           float64
TEACHSUP          float64
COGACRCO          float64
COGACMCO          float64
EXPOFA            float64
EXPO21ST          float64
MATHEFF           float64
MATHEF21          float64
FAMCON            float64
ANXMAT            float64
MATHPERS          float64
SCHSUST           float64
LEARRES           float64
PROBSELF          float64
FAMSUPSL          float64
FEELLAH           float64
SDLEFF            float64
MISCED              int64
FISCED              int64
HISCED              int64
PAREDINT          float64
BMMJ1             float64
BFMJ2             float64
HISEI             float64
ICTRES            float64
HOMEPOS           float64
ESCS              float64
ICTSCH            float64
ICTAVSCH            int64
ICTHOME           float64
ICTAVHOM            int64
ICTQUAL           float64
ICTSUBJ           float64
ICTENQ            float64
ICTFEED           float64
ICTOUT            float64
ICTWKDY             int64
ICTWKEND            int64
ICTREG            float64
ICTINFO           float64
ICTDISTR            int64
ICTEFFIC          float64
W_FSTUWT          float64
W_FSTURWT1        float64
W_FSTURWT2        float64
W_FSTURWT3        float64
W_FSTURWT4        float64
W_FSTURWT5        float64
W_FSTURWT6        float64
W_FSTURWT7        float64
W_FSTURWT8        float64
W_FSTURWT9        float64
W_FSTURWT10       float64
W_FSTURWT11       float64
W_FSTURWT12       float64
W_FSTURWT13       float64
W_FSTURWT14       float64
W_FSTURWT15       float64
W_FSTURWT16       float64
W_FSTURWT17       float64
W_FSTURWT18       float64
W_FSTURWT19       float64
W_FSTURWT20       float64
W_FSTURWT21       float64
W_FSTURWT22       float64
W_FSTURWT23       float64
W_FSTURWT24       float64
W_FSTURWT25       float64
W_FSTURWT26       float64
W_FSTURWT27       float64
W_FSTURWT28       float64
W_FSTURWT29       float64
W_FSTURWT30       float64
W_FSTURWT31       float64
W_FSTURWT32       float64
W_FSTURWT33       float64
W_FSTURWT34       float64
W_FSTURWT35       float64
W_FSTURWT36       float64
W_FSTURWT37       float64
W_FSTURWT38       float64
W_FSTURWT39       float64
W_FSTURWT40       float64
W_FSTURWT41       float64
W_FSTURWT42       float64
W_FSTURWT43       float64
W_FSTURWT44       float64
W_FSTURWT45       float64
W_FSTURWT46       float64
W_FSTURWT47       float64
W_FSTURWT48       float64
W_FSTURWT49       float64
W_FSTURWT50       float64
W_FSTURWT51       float64
W_FSTURWT52       float64
W_FSTURWT53       float64
W_FSTURWT54       float64
W_FSTURWT55       float64
W_FSTURWT56       float64
W_FSTURWT57       float64
W_FSTURWT58       float64
W_FSTURWT59       float64
W_FSTURWT60       float64
W_FSTURWT61       float64
W_FSTURWT62       float64
W_FSTURWT63       float64
W_FSTURWT64       float64
W_FSTURWT65       float64
W_FSTURWT66       float64
W_FSTURWT67       float64
W_FSTURWT68       float64
W_FSTURWT69       float64
W_FSTURWT70       float64
W_FSTURWT71       float64
W_FSTURWT72       float64
W_FSTURWT73       float64
W_FSTURWT74       float64
W_FSTURWT75       float64
W_FSTURWT76       float64
W_FSTURWT77       float64
W_FSTURWT78       float64
W_FSTURWT79       float64
W_FSTURWT80       float64
UNIT                int64
WVARSTRR            int64
PV1MATH           float64
PV2MATH           float64
PV3MATH           float64
PV4MATH           float64
PV5MATH           float64
PV6MATH           float64
PV7MATH           float64
PV8MATH           float64
PV9MATH           float64
PV10MATH          float64
PV1READ           float64
PV2READ           float64
PV3READ           float64
PV4READ           float64
PV5READ           float64
PV6READ           float64
PV7READ           float64
PV8READ           float64
PV9READ           float64
PV10READ          float64
PV1SCIE           float64
PV2SCIE           float64
PV3SCIE           float64
PV4SCIE           float64
PV5SCIE           float64
PV6SCIE           float64
PV7SCIE           float64
PV8SCIE           float64
PV9SCIE           float64
PV10SCIE          float64
PV1MCCR           float64
PV2MCCR           float64
PV3MCCR           float64
PV4MCCR           float64
PV5MCCR           float64
PV6MCCR           float64
PV7MCCR           float64
PV8MCCR           float64
PV9MCCR           float64
PV10MCCR          float64
PV1MCQN           float64
PV2MCQN           float64
PV3MCQN           float64
PV4MCQN           float64
PV5MCQN           float64
PV6MCQN           float64

In [4]:
replacements = {
    'object' : 'varchar(20)',
    'float64' : 'float',
    'init64' : 'int',
    'datetime64': 'timestamp'
}

col_str = ", ".join("{} {}".format(n,d) for (n,d) in zip(pisa2022_school_df.columns, pisa2022_school_df.dtypes.replace(replacements)))
col_str

'ï»¿CNT varchar(20), CNTRYID int64, CNTSCHID int64, CNTSTUID int64, CYC varchar(20), NatCen int64, STRATUM varchar(20), SUBNATIO int64, REGION int64, OECD varchar(20), ADMINMODE int64, LANGTEST_QQQ int64, LANGTEST_COG int64, Option_ICTQ int64, Option_WBQ int64, Option_PQ int64, Option_TQ int64, Option_UH int64, BOOKID int64, ST001D01T int64, ST003D02T int64, ST003D03T int64, ST004D01T int64, ST250Q01JA int64, ST250Q02JA int64, ST250Q03JA int64, ST250Q04JA int64, ST250Q05JA int64, ST250D06JA int64, ST250D07JA int64, ST251Q01JA int64, ST251Q02JA int64, ST251Q03JA int64, ST251Q04JA int64, ST251Q06JA int64, ST251Q07JA int64, ST251D08JA int64, ST251D09JA int64, ST253Q01JA int64, ST254Q01JA int64, ST254Q02JA int64, ST254Q03JA int64, ST254Q04JA int64, ST254Q05JA int64, ST254Q06JA int64, ST255Q01JA int64, ST256Q01JA int64, ST256Q02JA int64, ST256Q03JA int64, ST256Q06JA int64, ST256Q07JA int64, ST256Q08JA int64, ST256Q09JA int64, ST256Q10JA int64, ST230Q01JA int64, ST005Q01JA int64, ST006Q01JA int64, ST006Q02JA int64, ST006Q03JA int64, ST006Q04JA int64, ST006Q05JA int64, ST007Q01JA int64, ST008Q01JA int64, ST008Q02JA int64, ST008Q03JA int64, ST008Q04JA int64, ST008Q05JA int64, ST258Q01JA int64, ST259Q01JA int64, ST259Q02JA int64, ST019AQ01T int64, ST019BQ01T int64, ST019CQ01T int64, ST022Q01TA int64, ST226Q01JA int64, ST125Q01NA int64, ST126Q01TA int64, ST127Q01TA int64, ST127Q02TA int64, ST127Q03TA int64, ST260Q01JA int64, ST260Q02JA int64, ST260Q03JA int64, ST062Q01TA int64, ST062Q02TA int64, ST062Q03TA int64, ST267Q01JA int64, ST267Q02JA int64, ST267Q03JA int64, ST267Q04JA int64, ST267Q05JA int64, ST267Q06JA int64, ST267Q07JA int64, ST267Q08JA int64, ST034Q01TA int64, ST034Q02TA int64, ST034Q03TA int64, ST034Q04TA int64, ST034Q05TA int64, ST034Q06TA int64, ST038Q03NA int64, ST038Q04NA int64, ST038Q05NA int64, ST038Q06NA int64, ST038Q07NA int64, ST038Q08NA int64, ST038Q09JA int64, ST038Q10JA int64, ST038Q11JA int64, ST265Q01JA int64, ST265Q02JA int64, ST265Q03JA int64, ST265Q04JA int64, ST266Q01JA int64, ST266Q02JA int64, ST266Q03JA int64, ST266Q04JA int64, ST266Q05JA int64, ST294Q01JA int64, ST294Q02JA int64, ST294Q03JA int64, ST294Q04JA int64, ST294Q05JA int64, ST295Q01JA int64, ST295Q02JA int64, ST295Q03JA int64, ST295Q04JA int64, ST295Q05JA int64, ST326Q01JA int64, ST326Q02JA int64, ST326Q03JA int64, ST326Q04JA int64, ST326Q05JA int64, ST326Q06JA int64, ST322Q01JA int64, ST322Q02JA int64, ST322Q03JA int64, ST322Q04JA int64, ST322Q06JA int64, ST322Q07JA int64, ST307Q01JA int64, ST307Q02JA int64, ST307Q03JA int64, ST307Q04JA int64, ST307Q05JA int64, ST307Q06JA int64, ST307Q07JA int64, ST307Q08JA int64, ST307Q09JA int64, ST307Q10JA int64, ST309Q01JA int64, ST309Q02JA int64, ST309Q03JA int64, ST309Q04JA int64, ST309Q05JA int64, ST309Q06JA int64, ST309Q07JA int64, ST309Q08JA int64, ST309Q09JA int64, ST309Q10JA int64, ST301Q01JA int64, ST301Q02JA int64, ST301Q03JA int64, ST301Q04JA int64, ST301Q05JA int64, ST301Q06JA int64, ST301Q07JA int64, ST301Q08JA int64, ST301Q09JA int64, ST301Q10JA int64, ST343Q01JA int64, ST343Q02JA int64, ST343Q03JA int64, ST343Q04JA int64, ST343Q05JA int64, ST343Q06JA int64, ST343Q07JA int64, ST343Q08JA int64, ST343Q09JA int64, ST343Q10JA int64, ST311Q01JA int64, ST311Q02JA int64, ST311Q03JA int64, ST311Q04JA int64, ST311Q05JA int64, ST311Q06JA int64, ST311Q07JA int64, ST311Q08JA int64, ST311Q09JA int64, ST311Q10JA int64, ST315Q01JA int64, ST315Q02JA int64, ST315Q03JA int64, ST315Q04JA int64, ST315Q05JA int64, ST315Q06JA int64, ST315Q07JA int64, ST315Q08JA int64, ST315Q09JA int64, ST315Q10JA int64, ST303Q01JA int64, ST303Q02JA int64, ST303Q03JA int64, ST303Q04JA int64, ST303Q05JA int64, ST303Q06JA int64, ST303Q07JA int64, ST303Q08JA int64, ST305Q01JA int64, ST305Q02JA int64, ST305Q03JA int64, ST305Q04JA int64, ST305Q05JA int64, ST305Q06JA int64, ST305Q07JA int64, ST305Q08JA int64, ST305Q09JA int64, ST305Q10JA int64, ST345Q01JA int64, ST345Q02JA int64, ST345Q03JA int64, ST345Q04JA int64, ST345Q05JA int64, ST345Q06JA int64, ST345Q07JA int64, ST345Q08JA int64, ST345Q09JA int64, ST345Q10JA int64, ST313Q01JA int64, ST313Q02JA int64, ST313Q03JA int64, ST313Q04JA int64, ST313Q05JA int64, ST313Q06JA int64, ST313Q07JA int64, ST313Q08JA int64, ST313Q09JA int64, ST313Q10JA int64, ST263Q02JA int64, ST263Q04JA int64, ST263Q06JA int64, ST016Q01NA int64, ST059Q01TA int64, ST059Q02JA int64, ST296Q01JA int64, ST296Q02JA int64, ST296Q03JA int64, ST296Q04JA int64, ST272Q01JA int64, ST273Q01JA int64, ST273Q02JA int64, ST273Q03JA int64, ST273Q04JA int64, ST273Q05JA int64, ST273Q06JA int64, ST273Q07JA int64, ST270Q01JA int64, ST270Q02JA int64, ST270Q03JA int64, ST270Q04JA int64, ST285Q01JA int64, ST285Q02JA int64, ST285Q03JA int64, ST285Q04JA int64, ST285Q05JA int64, ST285Q06JA int64, ST285Q07JA int64, ST285Q08JA int64, ST285Q09JA int64, ST283Q01JA int64, ST283Q02JA int64, ST283Q03JA int64, ST283Q04JA int64, ST283Q05JA int64, ST283Q06JA int64, ST283Q07JA int64, ST283Q08JA int64, ST283Q09JA int64, ST275Q01WA int64, ST275Q02WA int64, ST275Q03WA int64, ST275Q04WA int64, ST275Q05WA int64, ST275Q06WA int64, ST275Q07WA int64, ST275Q08WA int64, ST275Q09WA int64, ST276Q01JA int64, ST276Q02JA int64, ST276Q03JA int64, ST276Q04JA int64, ST276Q05JA int64, ST276Q06JA int64, ST276Q07JA int64, ST276Q08JA int64, ST276Q09JA int64, ST276Q10JA int64, ST268Q01JA int64, ST268Q02JA int64, ST268Q03JA int64, ST268Q04JA int64, ST268Q05JA int64, ST268Q06JA int64, ST268Q07JA int64, ST268Q08JA int64, ST268Q09JA int64, ST290Q01WA int64, ST290Q02WA int64, ST290Q03WA int64, ST290Q04WA int64, ST290Q05WA int64, ST290Q06WA int64, ST290Q07WA int64, ST290Q08WA int64, ST290Q09WA int64, ST291Q01JA int64, ST291Q02JA int64, ST291Q03JA int64, ST291Q04JA int64, ST291Q05JA int64, ST291Q06JA int64, ST291Q07JA int64, ST291Q08JA int64, ST291Q09JA int64, ST291Q10JA int64, ST289Q01WA int64, ST289Q02JA int64, ST289Q03WA int64, ST289Q04JA int64, ST289Q05WA int64, ST289Q06JA int64, ST289Q07JA int64, ST289Q08WA int64, ST289Q09WA int64, ST289Q10WA int64, ST289Q11WA int64, ST289Q14JA int64, ST293Q01JA int64, ST293Q02JA int64, ST293Q03JA int64, ST293Q04JA int64, ST293Q05JA int64, ST293Q06JA int64, ST293Q07JA int64, ST293Q08JA int64, ST293Q09JA int64, ST292Q01JA int64, ST292Q02JA int64, ST292Q03JA int64, ST292Q04JA int64, ST292Q05JA int64, ST292Q06JA int64, ST297Q01JA int64, ST297Q03JA int64, ST297Q05JA int64, ST297Q06JA int64, ST297Q07JA int64, ST297Q09JA int64, ST300Q01JA int64, ST300Q02JA int64, ST300Q03JA int64, ST300Q04JA int64, ST300Q05JA int64, ST300Q06JA int64, ST300Q07JA int64, ST300Q08JA int64, ST300Q09JA int64, ST300Q10JA int64, ST327Q01JA int64, ST327Q02JA int64, ST327Q03JA int64, ST327Q04JA int64, ST327Q05JA int64, ST327Q06JA int64, ST327Q07JA int64, ST327Q08JA int64, ST330Q01WA int64, ST330Q02WA int64, ST330Q03WA int64, ST330Q04WA int64, ST330Q05WA int64, ST330Q06WA int64, ST330Q07WA int64, ST330Q08WA int64, ST330Q09WA int64, ST330Q11WA int64, ST330D10WA int64, ST324Q02JA int64, ST324Q04JA int64, ST324Q05JA int64, ST324Q07JA int64, ST324Q10JA int64, ST324Q11JA int64, ST324Q12JA int64, ST324Q13JA int64, ST324Q14JA int64, ST347Q01JA int64, ST347Q02JA int64, ST348Q01JA int64, ST348Q02JA int64, ST348Q03JA int64, ST348Q04JA int64, ST348Q05JA int64, ST348Q06JA int64, ST348Q07JA int64, ST348Q08JA int64, ST349Q01JA int64, ST350Q01JA int64, ST351Q01JA int64, ST351Q02JA int64, ST351Q03JA int64, ST351Q04JA int64, ST351Q05JA int64, ST351Q06JA int64, ST351Q07JA int64, ST351Q08JA int64, ST352Q01JA int64, ST352Q02JA int64, ST352Q03JA int64, ST352Q04JA int64, ST352Q05JA int64, ST352Q06JA int64, ST352Q07JA int64, ST352Q08JA int64, ST353Q01JA int64, ST353Q02JA int64, ST353Q03JA int64, ST353Q04JA int64, ST353Q05JA int64, ST353Q06JA int64, ST353Q07JA int64, ST353Q08JA int64, ST354Q01JA int64, ST354Q02JA int64, ST354Q03JA int64, ST354Q04JA int64, ST354Q05JA int64, ST354Q06JA int64, ST354Q07JA int64, ST354Q08JA int64, ST354Q09JA int64, ST354Q10JA int64, ST355Q01JA int64, ST355Q02JA int64, ST355Q03JA int64, ST355Q04JA int64, ST355Q05JA int64, ST355Q06JA int64, ST355Q07JA int64, ST355Q08JA int64, ST356Q01JA int64, ST331Q01JA int64, ST331Q02JA int64, ST331Q03JA int64, IC170Q01JA int64, IC170Q02JA int64, IC170Q03JA int64, IC170Q04JA int64, IC170Q05JA int64, IC170Q06JA int64, IC170Q07JA int64, IC171Q01JA int64, IC171Q02JA int64, IC171Q03JA int64, IC171Q04JA int64, IC171Q05JA int64, IC171Q06JA int64, IC172Q01JA int64, IC172Q02JA int64, IC172Q03JA int64, IC172Q04JA int64, IC172Q05JA int64, IC172Q06JA int64, IC172Q07JA int64, IC172Q08JA int64, IC172Q09JA int64, IC173Q01JA int64, IC173Q02JA int64, IC173Q03JA int64, IC173Q04JA int64, IC174Q01JA int64, IC174Q02JA int64, IC174Q03JA int64, IC174Q04JA int64, IC174Q05JA int64, IC174Q06JA int64, IC174Q07JA int64, IC174Q08JA int64, IC174Q09JA int64, IC174Q10JA int64, IC175Q01JA int64, IC175Q02JA int64, IC175Q03JA int64, IC175Q05JA int64, IC176Q01JA int64, IC176Q02JA int64, IC176Q03JA int64, IC176Q04JA int64, IC176Q05JA int64, IC176Q06JA int64, IC176Q07JA int64, IC176Q08JA int64, IC184Q01JA int64, IC184Q02JA int64, IC184Q03JA int64, IC184Q04JA int64, IC177Q01JA int64, IC177Q02JA int64, IC177Q03JA int64, IC177Q04JA int64, IC177Q05JA int64, IC177Q06JA int64, IC177Q07JA int64, IC178Q01JA int64, IC178Q02JA int64, IC178Q03JA int64, IC178Q04JA int64, IC178Q05JA int64, IC178Q06JA int64, IC178Q07JA int64, IC179Q01JA int64, IC179Q02JA int64, IC179Q03JA int64, IC179Q04JA int64, IC179Q05JA int64, IC179Q06JA int64, IC180Q01JA int64, IC180Q02JA int64, IC180Q03JA int64, IC180Q04JA int64, IC180Q05JA int64, IC180Q06JA int64, IC180Q07JA int64, IC180Q08JA int64, IC181Q01JA int64, IC181Q02JA int64, IC181Q03JA int64, IC181Q04JA int64, IC182Q01JA int64, IC182Q02JA int64, IC182Q03JA int64, IC183Q01JA int64, IC183Q02JA int64, IC183Q03JA int64, IC183Q04JA int64, IC183Q05JA int64, IC183Q07JA int64, IC183Q08JA int64, IC183Q09JA int64, IC183Q10JA int64, IC183Q12JA int64, IC183Q13JA int64, IC183Q14JA int64, IC183Q15JA int64, IC183Q16JA int64, EFFORT1 int64, EFFORT2 int64, OCOD1 int64, OCOD2 int64, OCOD3 int64, PROGN int64, AGE float, GRADE int64, ISCEDP int64, IMMIG int64, COBN_S int64, COBN_M int64, COBN_F int64, LANGN int64, REPEAT int64, MISSSC int64, SKIPPING int64, TARDYSD int64, EXERPRAC int64, STUDYHMW int64, WORKPAY int64, WORKHOME int64, EXPECEDU int64, MATHPREF int64, MATHEASE int64, MATHMOT int64, DURECEC int64, BSMJ float, SISCO int64, RELATST float, BELONG float, BULLIED float, FEELSAFE float, SCHRISK float, PERSEVAGR int64, CURIOAGR float, COOPAGR int64, EMPATAGR int64, ASSERAGR int64, STRESAGR int64, EMOCOAGR int64, INFOSEEK float, FAMSUP float, DISCLIM float, TEACHSUP float, COGACRCO float, COGACMCO float, EXPOFA float, EXPO21ST float, MATHEFF float, MATHEF21 float, FAMCON float, ANXMAT float, MATHPERS float, SCHSUST float, LEARRES float, PROBSELF float, FAMSUPSL float, FEELLAH float, SDLEFF float, MISCED int64, FISCED int64, HISCED int64, PAREDINT float, BMMJ1 float, BFMJ2 float, HISEI float, ICTRES float, HOMEPOS float, ESCS float, ICTSCH float, ICTAVSCH int64, ICTHOME float, ICTAVHOM int64, ICTQUAL float, ICTSUBJ float, ICTENQ float, ICTFEED float, ICTOUT float, ICTWKDY int64, ICTWKEND int64, ICTREG float, ICTINFO float, ICTDISTR int64, ICTEFFIC float, W_FSTUWT float, W_FSTURWT1 float, W_FSTURWT2 float, W_FSTURWT3 float, W_FSTURWT4 float, W_FSTURWT5 float, W_FSTURWT6 float, W_FSTURWT7 float, W_FSTURWT8 float, W_FSTURWT9 float, W_FSTURWT10 float, W_FSTURWT11 float, W_FSTURWT12 float, W_FSTURWT13 float, W_FSTURWT14 float, W_FSTURWT15 float, W_FSTURWT16 float, W_FSTURWT17 float, W_FSTURWT18 float, W_FSTURWT19 float, W_FSTURWT20 float, W_FSTURWT21 float, W_FSTURWT22 float, W_FSTURWT23 float, W_FSTURWT24 float, W_FSTURWT25 float, W_FSTURWT26 float, W_FSTURWT27 float, W_FSTURWT28 float, W_FSTURWT29 float, W_FSTURWT30 float, W_FSTURWT31 float, W_FSTURWT32 float, W_FSTURWT33 float, W_FSTURWT34 float, W_FSTURWT35 float, W_FSTURWT36 float, W_FSTURWT37 float, W_FSTURWT38 float, W_FSTURWT39 float, W_FSTURWT40 float, W_FSTURWT41 float, W_FSTURWT42 float, W_FSTURWT43 float, W_FSTURWT44 float, W_FSTURWT45 float, W_FSTURWT46 float, W_FSTURWT47 float, W_FSTURWT48 float, W_FSTURWT49 float, W_FSTURWT50 float, W_FSTURWT51 float, W_FSTURWT52 float, W_FSTURWT53 float, W_FSTURWT54 float, W_FSTURWT55 float, W_FSTURWT56 float, W_FSTURWT57 float, W_FSTURWT58 float, W_FSTURWT59 float, W_FSTURWT60 float, W_FSTURWT61 float, W_FSTURWT62 float, W_FSTURWT63 float, W_FSTURWT64 float, W_FSTURWT65 float, W_FSTURWT66 float, W_FSTURWT67 float, W_FSTURWT68 float, W_FSTURWT69 float, W_FSTURWT70 float, W_FSTURWT71 float, W_FSTURWT72 float, W_FSTURWT73 float, W_FSTURWT74 float, W_FSTURWT75 float, W_FSTURWT76 float, W_FSTURWT77 float, W_FSTURWT78 float, W_FSTURWT79 float, W_FSTURWT80 float, UNIT int64, WVARSTRR int64, PV1MATH float, PV2MATH float, PV3MATH float, PV4MATH float, PV5MATH float, PV6MATH float, PV7MATH float, PV8MATH float, PV9MATH float, PV10MATH float, PV1READ float, PV2READ float, PV3READ float, PV4READ float, PV5READ float, PV6READ float, PV7READ float, PV8READ float, PV9READ float, PV10READ float, PV1SCIE float, PV2SCIE float, PV3SCIE float, PV4SCIE float, PV5SCIE float, PV6SCIE float, PV7SCIE float, PV8SCIE float, PV9SCIE float, PV10SCIE float, PV1MCCR float, PV2MCCR float, PV3MCCR float, PV4MCCR float, PV5MCCR float, PV6MCCR float, PV7MCCR float, PV8MCCR float, PV9MCCR float, PV10MCCR float, PV1MCQN float, PV2MCQN float, PV3MCQN float, PV4MCQN float, PV5MCQN float, PV6MCQN float, PV7MCQN float, PV8MCQN float, PV9MCQN float, PV10MCQN float, PV1MCSS float, PV2MCSS float, PV3MCSS float, PV4MCSS float, PV5MCSS float, PV6MCSS float, PV7MCSS float, PV8MCSS float, PV9MCSS float, PV10MCSS float, PV1MCUD float, PV2MCUD float, PV3MCUD float, PV4MCUD float, PV5MCUD float, PV6MCUD float, PV7MCUD float, PV8MCUD float, PV9MCUD float, PV10MCUD float, PV1MPEM float, PV2MPEM float, PV3MPEM float, PV4MPEM float, PV5MPEM float, PV6MPEM float, PV7MPEM float, PV8MPEM float, PV9MPEM float, PV10MPEM float, PV1MPFS float, PV2MPFS float, PV3MPFS float, PV4MPFS float, PV5MPFS float, PV6MPFS float, PV7MPFS float, PV8MPFS float, PV9MPFS float, PV10MPFS float, PV1MPIN float, PV2MPIN float, PV3MPIN float, PV4MPIN float, PV5MPIN float, PV6MPIN float, PV7MPIN float, PV8MPIN float, PV9MPIN float, PV10MPIN float, PV1MPRE float, PV2MPRE float, PV3MPRE float, PV4MPRE float, PV5MPRE float, PV6MPRE float, PV7MPRE float, PV8MPRE float, PV9MPRE float, PV10MPRE float, SENWT float, i int64, Country_Region varchar(20), Ranking int64, AverageScore float'

In [7]:
username = 'root'
password = 'Owen01042545'
hostname = 'localhost'  # Usually 'localhost' if MySQL is running locally
database_name = 'pisa2022'


# Create connection string
connection_str = f'mysql+mysqlconnector://{username}:{password}@{hostname}/{database_name}'

# Connect to MySQL
engine = create_engine(connection_str)
connection = engine.connect()

# Example SQL query
query = 'SELECT * FROM pisa2022_data'
df = pd.read_sql(query, connection)

# Close connection
connection.close()

# Display the dataframe
df.head()

Empty DataFrame
Columns: [CNT, CNTRYID, CNTSCHID, CNTSTUID, CYC, NatCen, STRATUM, SUBNATIO, REGION, OECD, ADMINMODE, LANGTEST_QQQ, LANGTEST_COG, Option_ICTQ, Option_WBQ, Option_PQ, Option_TQ, Option_UH, BOOKID, ST001D01T, ST003D02T, ST003D03T, ST004D01T, ST250Q01JA, ST250Q02JA, ST250Q03JA, ST250Q04JA, ST250Q05JA, ST250D06JA, ST250D07JA, ST251Q01JA, ST251Q02JA, ST251Q03JA, ST251Q04JA, ST251Q06JA, ST251Q07JA, ST251D08JA, ST251D09JA, ST253Q01JA, ST254Q01JA, ST254Q02JA, ST254Q03JA, ST254Q04JA, ST254Q05JA, ST254Q06JA, ST255Q01JA, ST256Q01JA, ST256Q02JA, ST256Q03JA, ST256Q06JA, ST256Q07JA, ST256Q08JA, ST256Q09JA, ST256Q10JA, ST230Q01JA, ST005Q01JA, ST006Q01JA, ST006Q02JA, ST006Q03JA, ST006Q04JA, ST006Q05JA, ST007Q01JA, ST008Q01JA, ST008Q02JA, ST008Q03JA, ST008Q04JA, ST008Q05JA, ST258Q01JA, ST259Q01JA, ST259Q02JA, ST019AQ01T, ST019BQ01T, ST019CQ01T, ST022Q01TA, ST226Q01JA, ST125Q01NA, ST126Q01TA, ST127Q01TA, ST127Q02TA, ST127Q03TA, ST260Q01JA, ST260Q02JA, ST260Q03JA, ST062Q01TA, ST062Q02TA, ST062Q03TA, ST267Q01JA, ST267Q02JA, ST267Q03JA, ST267Q04JA, ST267Q05JA, ST267Q06JA, ST267Q07JA, ST267Q08JA, ST034Q01TA, ST034Q02TA, ST034Q03TA, ST034Q04TA, ST034Q05TA, ST034Q06TA, ...]
Index: []

[0 rows x 838 columns]

In [9]:
pisa2022_school_df.to_sql('pisa2022_data', con=engine, if_exists='append', index=False)